### ISSUE TITLE
Context.resolvePath

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [Rezmason/Golems#3]
Hey,

When build for ios the "buildPath" going into "Golem::rise" has to be modified using something like

```
buildPath = haxe.macro.Context.resolvePath(buildPath);
```

I have little expirience with macros, so I am not sure if this code part should go into "Golem.hx" or if any time rise is called, the path should go through "resolvePath" before being passed to rise.

**Comment by Rezmason** [comment]
Hey, sorry for the late reply! I'm unsure why the path needs to change for iOS, having never used that target before; if there's an iOS compiler flag, and if this problem presumably affects all iOS builds, would you be willing to test your proposed modification within a compiler condition? Ideally I'd accept a Git pull request, but sending me a Gist of your modified Golem.hx file would suffice, assuming your proposed change works. :)

**Comment by RudolfVonKrugstein** [comment]
Hey, the original discussion is here: http://community.openfl.org/t/solved-files-used-during-macro-time-not-found-on-ios/1189/4

I can make a small pull request and test it for android, ios, max and linux.

What exactly do you mean by "within a compiler condition"?

**Comment by Rezmason** [comment]
These are what I call compiler conditions: #if (flash || cpp) foo #else bar #end
If you request it, I'll run the existing tests on it, and assuming those check out, in it goes! :-)

**Comment by Rezmason** [comment]
Pull request accepted! Also fixed an issue with error handling.
