### ISSUE TITLE
What is BasicWorker.__initAliases for?

### ISSUE THREAD

**Issue by explorigin** [Rezmason/Golems#5]
Nice little library you have here.  I'm wondering what BasicWorker.__initAliases is used for.  I can't find anything other than it just existing.

**Comment by Rezmason** [comment]
Sorry for the late reply!

You're right, `__initAliases` serves no purpose. I'll remove it with the next update. :+1:

(It used to be the staging ground for some macro-driven calls to `registerClassAlias` for the Flash target, but then I wised up and switched all the targets to using the Haxe serializer.)
